[package]
name = "valence_command"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
bevy_ecs.workspace = true
bevy_app.workspace = true
bevy_hierarchy.workspace = true
valence_core.workspace = true
anyhow.workspace = true
glam.workspace = true
serde_json.workspace = true
serde.workspace = true
valence_client.workspace = true
valence_block.workspace = true
valence_nbt.workspace = true
valence_entity.workspace = true
valence_instance.workspace = true
ctor.workspace = true
casey.workspace = true
paste.workspace = true
rustc-hash.workspace = true